### ISSUE TITLE
Request for Clarification on Project Licensing with GPL and AGPL Dependencies"

### ISSUE THREAD

**Issue by 1aienthusiast** [sasha0552/ToriLinux#36]
I'm wondering if it's appropriate to license the project under the MIT license, given that it's built on top of Arch Linux (which is licensed under GPL) and includes several repositories that are licensed under AGPL (such as text-generation-webui, sillytavern, and automatic). Could you please clarify the licensing considerations for this project?

**Comment by sasha0552** [comment]
This project does not contain those projects directly, and all my changes (e.g. patches) or build scripts are under MIT (which is anyway GPL/AGPL/etc compatible, because these licenses are more stricter than MIT).
Configuration files (99% of this project) are not subject to licensing, only code.
