### ISSUE TITLE
InvokeAI 

### ISSUE THREAD

**Issue by MylesCroft** [sasha0552/ToriLinux#40]
Can you include InvokeAI into the mix as an alternative image generator?

https://github.com/invoke-ai/InvokeAI

**Comment by sasha0552** [comment]
Added https://github.com/sasha0552/ToriLinux/commit/6408517f2391fddbfe93fca72cdc1cc17474179c

Should be available as `invokeai-web` (I haven't checked if it works correctly, though).

**Comment by sasha0552** [comment]
I've tested it, it works.

![file](https://github.com/user-attachments/assets/14f84d92-1572-465c-9913-c56024ad782f)
